storage-accounts.tf

Added processing container
```
[ ] Yes
[x] No
```

Added new processing container

---

application-insights.tf
key-vaults.tf

https://tools.hmcts.net/jira/browse/HMIS-1185
Added IaC for application insights which will be used for the new rota dtu.
```
[ ] Yes
[x] No
```

HMIS-1185 Application Insights

---

key-vaults.tf

Added app insights connection string to KV.
```
[ ] Yes
[x] No
```

Added app insights connection string

---

key-vaults.tf

Added infra to transfer manual secrets from bootstrap KV to main KV.
```
[ ] Yes
[x] No
```

Added bootstrap KV transfer

---

README.md

Update shared infra
```
[ ] Yes
[x] No
```

Update shared infra

---

storage-accounts.tf

Update adding in enable_change_feed due to change in module.
```
[ ] Yes
[x] No
```

Update sa module change

---

application-insights.tf
key-vaults.tf
storage-accounts.tf

https://tools.hmcts.net/jira/browse/HMIS-1172
Setup the infra for the libra dtu.
```
[ ] Yes
[x] No
```

HMIS-1172 Libra infra

---

key-vaults.tf

https://tools.hmcts.net/jira/browse/HMIS-1168
Add service now secrets to the key vault.
[ ] Yes
[x] No

HMIS-1168 Create ServiceNow Secrets

---

automation-account.tf
automation-sas-tokens.tf
key-vaults.tf
main.tf
variables.tf

https://tools.hmcts.net/jira/browse/HMIS-1193
Added in automation accounts for SAS token refresh and new KVs dedicated for these SAS tokens which will be shared with ROTA.
```
[ ] Yes
[x] No
```

ROTA SAS token automation

---

automation-sas-tokens.tf

Removed bypass networking.
```
[ ] Yes
[x] No
```

removed bypass networking

---

key-vault-access-policy.tf
key-vaults.tf

Update KV access policy for automation.
```
[ ] Yes
[x] No
```

Updated KV access policy

---

key-vaults.tf

Added SA name to KVs.
```
[ ] Yes
[x] No
```

Added sa name to KVs

---

key-vaults.tf

Added MI id to KV.
```
[ ] Yes
[x] No
```

Added MI id to KV

---

key-vaults.tf

update id to client_id

---

cft-client-key-vaults.tf
crime-client-key-vaults.tf
hmi-key-vaults.tf
main.tf
rota-client-key-vaults.tf
snl-client-key-vaults.tf
variables.tf

https://tools.hmcts.net/jira/browse/HMIS-1214
Updated list of secrets that need to be pulled from bootstrap KV to main HMI KV
Added new KVs for HMI clients
Added pulling client id/secret from bootstrap KV to new client KVs
```
[ ] Yes
[x] No
```

HMIS-1214 Move over secrets

---

key-vault-access-policy.tf
main.tf

Add SDS APIM SP to KV.
```
[ ] Yes
[x] No
```

Add SDS APIM SP to KV

---

.github/workflows/terraform_format.yml
automation-account.tf
automation-sas-tokens.tf
cft-client-key-vaults.tf
crime-client-key-vaults.tf
demo.tfvars
dev.tfvars
hmi-key-vaults.tf
ithc.tfvars
main.tf
rota-client-key-vaults.tf
sbox.tfvars
snl-client-key-vaults.tf
stg.tfvars
storage-accounts.tf
test.tfvars

Added action to format terraform.
```
[ ] Yes
[x] No
```

Added action for terraform format

---

hmi-key-vaults-crime-certs.tf
hmi-key-vaults.tf

Move crime cert from bootstrap to main kv.
```
[ ] Yes
[x] No
```

HMIS-1273 Move crime cert from bootstrap to main kv

---

Jenkinsfile_CNP

Unable to see the this repo in Jenkins

Fix Jenkins visibility issue

---

state.tf
storage-accounts.tf
variables.tf

Fix jenkins build

---

Jenkinsfile_CNP

revert the change

---

application-insights.tf
automation-account.tf
automation-sas-tokens.tf
cft-client-key-vaults.tf
crime-client-key-vaults.tf
hmi-key-vaults.tf
main.tf
rota-client-key-vaults.tf
snl-client-key-vaults.tf
storage-accounts.tf

switched resource group to new created one managed by this repo

switched resource group to new created one managed by this repo

---

README.md
automation-account.tf
automation-sas-tokens.tf
cft-client-key-vaults.tf
crime-client-key-vaults.tf
hmi-key-vaults.tf
rota-client-key-vaults.tf
snl-client-key-vaults.tf

- Updated KV names
- Temp removed automation account so storage account can be re-created correctly
- Removed KV secret expiry dates

Update KV names

---

hmi-key-vaults.tf
main.tf
storage-accounts.tf

Re create storage accounts

---

automation-account.tf
automation-sas-tokens.tf

Added automation accounts back

Added automation accounts back

---

main.tf
variables.tf

Added common tags for MI and removed unused var.

Added common tags for MI

---

automation-account.tf
automation-sas-tokens.tf
hmi-key-vaults.tf
key-vault-access-policy.tf
main.tf
storage-accounts.tf

switched over to new mi

---

application-insights.tf
automation-account.tf
hmi-key-vaults.tf
key-vault-access-policy.tf
main.tf
storage-accounts.tf

Remove libra infra and add depends on

Remove libra infra and add depends on

---

prod.tfvars

Added prod.tfvars for when we enable prod.

Added prod.tfvars

---

hmi-key-vaults.tf
main.tf

Switched mi back

---

dlrm-client-key-vaults.tf

https://tools.hmcts.net/jira/browse/HMIS-1337
Add DLRM secret in azure keyvault.

HMIS-1337 Add DLRM secret

---

README.md

Run pipeline

---

README.md

https://tools.hmcts.net/jira/browse/PUB-2400
Update ReadMe File.

PUB-2400 Update Readme file

---

README.md

https://tools.hmcts.net/jira/browse/PUB-2540
Rerun the pipeline to move secrets from bootstrap to main keyvaults.

PUB-2540 Update CFT credentials

---

state.tf

https://tools.hmcts.net/jira/browse/PUB-2959
Dependency Updates

PUB-2959 - Updated versions
